name: Generate Cypress Report
on:
  push
  # workflow_dispatch:
  #   inputs:
  #     name:
  #       description: 'Cypress test'
  #       default: 'run'
  #       required: true
  #       type: string
  # schedule:
  #   - cron: '30 16 * * 1-5'
 
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    env:
      CYPRESS_REPORT_CONTENT: ''
      timestamp: ''
      cypress_username_admin: ${{ vars.cypress_username_admin }}
      cypress_password_admin: ${{ vars.cypress_password_admin }}
      cypress_username_hiringmanager: ${{ vars.cypress_username_hiringmanager }}
      cypress_password_hiringmanager: ${{ vars.cypress_password_hiringmanager }}
      cypress_base_url: ${{ vars.cypress_base_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
     
      - name: Install dependencies
        run: npm install
        
      - name: Cypress run
        uses: cypress-io/github-action@v6.5.0
        with:
          browser: chrome

      - name: Set current date as env variable
        run: echo "timestamp=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Echo current date
        run: echo $timestamp
       
      - name: upload artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Talentsavvy-Cypress-Test-${{ env.timestamp }}
          path: cypress/reports/html
          retention-days: 30

      # - name: Read HTML content
      #   id: read-html
      #   run: |
      #     echo "::set-output name=html_content::$(cat cypress/reports/html/Ts-cypress_report.html)"

      - name: Read Cypress report content
        id: read-report
        run: |
          # Read HTML content from the generated file
          report_content=$(cat cypress/reports/html/Ts-cypress_report.html)
          echo “::set-output name=content::$report_content”

      - name: echo env variable
        run: echo "CYPRESS_REPORT_CONTENT=$report_content" >> $GITHUB_ENV

      - name: Echo content
        run: echo $CYPRESS_REPORT_CONTENT
        
      - name: List content of the directory
        run: ls -al cypress/reports/html
      
      - name: Send email with Cypress artifacts
        uses: dawidd6/action-send-mail@v3.9.0
        with:
            server_address: smtp-mail.outlook.com
            server_port: 587
            username: rajat@talentsavvy.com
            password: ${{ secrets.CYPRESS_SMTP_PASSWORD }}
            subject: "Cypress test results for ${{ github.repository }}"
            from: rajat@talentsavvy.com
            to: rajat@talentsavvy.com
            content-type: text/html
            html_body: file://readme.html
            attachments: |
              cypress/reports/html/*
          
