name: Generate Cypress Report testing
on:
  push:
    branches:
      - 'main'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install dependencies
        run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v6.5.0 # use the explicit version number
        with:
          command: npx cypress run ui-regression
      - name: Uploading artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-execution-report
          path: cypress/reports/html
          retention-days: 30
      - name: Get artifact ID from logs
        id: get-artifact-id
        run: |
          # Extract artifact ID from the raw logs
          artifact_id=$(echo "${{ job.outputs.upload-artifact }}" | grep -oP 'Artifact ID is \K\d+')

