name: Generate Cypress Report testing
on:
  push:
    branches:
      - 'main'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install dependencies
        run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v6.5.0 # use the explicit version number
        with:
          command: npx cypress run ui-regression
      - name: Uploading artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-execution-report
          path: cypress/reports/html
          retention-days: 30
      - name: Save logs to file
        run: echo "Step-specific logs" > step_logs.txt

  read_logs_job:
    needs: cypress-run
    runs-on: ubuntu-latest

    steps:
      # Download the artifact with logs
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: cypress-execution-report

      # Print the logs from the file
      - name: Print logs
        run: cat cypress-execution-report/step_logs.txt
