name: Generate Cypress Report testing
on:
  push:
    branches:
      - 'main'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    env:
      timestamp: ''
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      # - name: Set current date as env variable
      #   run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      # - name: Echo current date
      #   run: echo "${{ env.NOW }}"
        
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install dependencies
        run: npm install

      # - name: Cypress run
      #   uses: cypress-io/github-action@v6.5.0 # use the explicit version number
      #   with:
      #     browser: chrome
      - name: Cypress run
        uses: cypress-io/github-action@v6.5.0
        with:
          browser: chrome

      - name: Set current date as env variable
        run: echo "timestamp=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Echo current date
        run: echo $timestamp
       
      - name: upload artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Talentsavvy-Cypress-Test-Report-${{ env.timestamp }}
          path: cypress/reports/html
          retention-days: 30

      - name: echo values
        run: |
          # Get raw logs for a specific workflow run
          raw_logs=$(curl -s -H "Authorization: Bearer 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" "https://api.github.com/repos/rpaidalwar/cypress-reports-html/actions/runs/${{ github.run_id }}/logs")
          
          # Extract values using grep and awk
          tests=$(echo "$raw_logs" | grep -oP 'Tests\s+\K\d+')
          passing=$(echo "$raw_logs" | grep -oP 'Passing\s+\K\d+')
          failing=$(echo "$raw_logs" | grep -oP 'Failing\s+\K\d+')
          pending=$(echo "$raw_logs" | grep -oP 'Pending\s+\K\d+')
          skipped=$(echo "$raw_logs" | grep -oP 'Skipped\s+\K\d+')
          
          # Print extracted values
          echo "Tests: $tests"
          echo "Passing: $passing"
          echo "Failing: $failing"
          echo "Pending: $pending"
          echo "Skipped: $skipped"
              
      - name: Extract Cypress Summary from HTML
        run: |
          # Replace 'cypress/reports/html/*.html' with the actual path to your HTML file
          cypress_summary=$(grep -oP '<span class="totalTests">[^<]+' cypress/reports/html)
          echo "Cypress Summary: $cypress_summary"

      - name: Install Nodemailer
        run: npm install nodemailer

      - name: Send Email
        run: |
          # Extract Cypress test summary from the generated report
          cypress_summary=$(cat cypress/reports/html | jq -r '.totalTests .passes .failures')

          # Construct email content
          email_content="Cypress Test Summary:
          Total Tests: $cypress_summary"

          # Send email using nodemailer or your preferred email library
          # Note: Replace the placeholders with your email server details and credentials
          echo "$email_content" | node -e "const nodemailer = require('nodemailer'); const transporter = nodemailer.createTransport({ host: 'smtp-mail.outlook.com', port: 587, auth: { user: 'rajat@talentsavvy.com', pass: '*r32yvM7!p6A1' } }); transporter.sendMail({ from: 'rajat@talentsavvy.com', to: 'rajat@talentsavvy.com', subject: 'Cypress Test Summary', text: '$email_content' });"

      # - name: Cypress run
      #   uses: cypress-io/github-action@v6.5.0
      #   with:
      #     command: npx cypress run ui-regression
                    
  #     - name: Uploading artifact
  #       uses: actions/upload-artifact@v4
  #       if: always()
  #       with:
  #         name: cypress-execution-report
  #         path: cypress/reports/html
  #         retention-days: 30

  # download-and-send-to-teams:
  #     runs-on: ubuntu-latest
  #     if: always()
  #     needs: cypress-run
  #     steps:
  #       - name: Download artifact
  #         uses: actions/download-artifact@v4
  #         with:
  #           name: cypress-execution-report
  #           path: cypress/reports/html
  #       - name: List artifact contents
  #         run: ls -R cypress/reports/html
  #       # - name: Unzip artifact
  #       #   run: unzip -q cypress/reports/html/cypress-execution-report.zip -d cypress/reports/html/
  #       - name: Debugging
  #         run: |
  #           echo "Current directory: $(pwd)"
  #           echo "Contents of cypress/reports/html: $(ls cypress/reports/html)"

  #       - name: Read email recipients from file
  #         id: read_recipients
  #         run: |
  #           echo "::set-output name=email_recipients::$(cat email_recipients.txt | tr '\n' ',')"
  
  #       # - name: Send Cypress Report to Teams
  #       #   uses: simbo/msteams-message-card-action@latest
  #       #   with:
  #       #     webhook: ${{ secrets.CYPRESS_TEAMS_WEBHOOK }}
  #       #     message: |
  #       #       New Cypress Report Available!
  #       #       - **GitHub Run Number:** ${{ github.run_number }}
  #       #       - **Commit SHA:** ${{ github.sha }}
  #       #       - **Triggered by:** ${{ github.actor }}
  #       #       - **Run Time:** $NOW
  #       #       - Click on the link to download the report from GitHub.
  #       #       # Check the [Cypress Report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
  #       #     sections: 'cypress/reports/html/Ts-cypress_report.html'
  #     # - name: Download Cypress artifacts
  #     #   uses: actions/download-artifact@v4
  #     #   with:
  #     #     name: Ts-cypress_report
  #     #     path: cypress/reports/html/*
      
  #     # - name: Uploading artifact
  #     #   uses: actions/upload-artifact@v4
  #     #   if: always()
  #     #   with:
  #     #     name: Ts-cypress_report
  #     #     path: cypress/reports/html/* 
  # # Send-Email:
  # #     runs-on: ubuntu-latest
  # #     needs: cypress-run
  # #     if: always()
  # #     steps:
  # #       - name: Checkout
  # #         uses: actions/checkout@v4.1.1
  
  # #       - name: Download Cypress artifacts
  # #         uses: actions/download-artifact@v4
  # #         with:
  # #           name: cypress-execution-report
  # #           path: cypress/reports/html
  
  #       - name: Send email with Cypress artifacts
  #         uses: dawidd6/action-send-mail@v3.9.0
  #         with:
  #           server_address: smtp-mail.outlook.com
  #           server_port: 587
  #           username: rajat@talentsavvy.com
  #           password: ${{ secrets.CYPRESS_SMTP_PASSWORD }}
  #           subject: "Cypress test results for ${{ github.repository }}"
  #           body: |
  #             New Cypress Report Available!
  #             - **GitHub Run Number:** ${{ github.run_number }}
  #             - **Commit SHA:** ${{ github.sha }}
  #             - **Triggered by:** ${{ github.actor }}
  #             "Please find the attached Cypress test report."
  #           from: rajat@talentsavvy.com
  #           to: ${{ vars.EMAIL_RECIPIENTS }}
  #           attachments: |
  #             cypress/reports/html/*
