name: Generate Cypress Report testing
on:
  push:
    branches:
      - 'main'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install dependencies
        run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v6.5.0 # use the explicit version number
        with:
          command: npx cypress run ui-regression
      - name: Uploading artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-execution-report
          path: cypress/reports/html
          retention-days: 30
      - name: Extract Artifact ID
        run: |
          # Extracting Artifact ID using regex
          ARTIFACT_ID=$(echo "$GITHUB_EVENT_PATH" | jq -r '.workflow_run.artifacts[].id')

          # Setting the extracted Artifact ID as an environment variable
          echo "ARTIFACT_ID=$ARTIFACT_ID" >> $GITHUB_ENV

          echo "Extracted Artifact ID: $ARTIFACT_ID"
