name: Generate Cypress Report 
on:
  push
  # workflow_dispatch:
  #   inputs:
  #     name:
  #       description: 'Cypress test'
  #       default: 'run'
  #       required: true
  #       type: string
  # schedule:
  #   - cron: '30 16 * * 1-5'
 
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    env:
      report: ''
      timestamp: ''
      cypress_username_admin: ${{ vars.cypress_username_admin }}
      cypress_password_admin: ${{ vars.cypress_password_admin }}
      cypress_username_hiringmanager: ${{ vars.cypress_username_hiringmanager }}
      cypress_password_hiringmanager: ${{ vars.cypress_password_hiringmanager }}
      cypress_base_url: ${{ vars.cypress_base_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
     
      - name: Install dependencies
        run: npm install
        
      # - name: Cypress run
      #   uses: cypress-io/github-action@v6.5.0
      #   with:
      #     browser: chrome
      - name: Run Cypress tests
        run: npx cypress run -- --reporter json

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Talentsavvy-Cypress-Test-${{ env.timestamp }}
          path: cypress/reports/html

      - name: List content of the directory
        run: ls -al cypress/reports/html


      - name: Checkout
        uses: actions/checkout@v2
  
      - name: Pushes test file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'cypress/reports/html/Ts-cypress_report.html'
          destination_repo: 'rpaidalwar/html'
          destination_folder: '.'
          user_email: 'example@email.com'
          user_name: 'dmnemec'
          commit_message: 'A custom message for the commit'
      # - name: Commit and Push to Repository B
      #   run: |
      #     cp cypress/reports/html/Ts-cypress_report.html $GITHUB_WORKSPACE/Ts-cypress_report.html
      #     git add Ts-cypress_report.html
      #     git commit -m "Update HTML file"
      #     git push https://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@github.com/rpaidalwar/html.git HEAD:main
      # - name: Commit and Push to Repository B
      #   run: |
      #     cp cypress/reports/html/Ts-cypress_report.html $GITHUB_WORKSPACE/Ts-cypress_report.html
      #     git add Ts-cypress_report.html
      #     git commit -m "Update HTML file"
      #     git remote remove origin
      #     git remote add origin git@github.com:rpaidalwar/html.git
      #     # git remote add origin https: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@github.com/rpaidalwar/html.git
      #     git push origin HEAD:main
      # - name: Parse Cypress results
      #   run: |
      #     # Assuming your Cypress JSON report is located at cypress/reports/json/.json
      #     RESULTS=$(jq -r '.stats' cypress/reports/json/*.json)
      
      #     # Extract individual results
      #     PASSED=$(echo $RESULTS | jq -r '.passes')
      #     FAILED=$(echo $RESULTS | jq -r '.failures')
      #     PENDING=$(echo $RESULTS | jq -r '.pending')
      #     SKIPPED=$(echo $RESULTS | jq -r '.skipped')
      #     DURATION=$(echo $RESULTS | jq -r '.duration')
      
      #     echo "Cypress Results:"
      #     echo "Result   Passed ✅   Failed ❌   Pending ✋   Skipped ↩️   Duration 🕗"
      #     echo "Passing  ✅          $PASSED     $FAILED     $PENDING     $SKIPPED      $DURATION"
      #   shell: bash
  
      # - name: Set current date as env variable
      #   run: echo "timestamp=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      # - name: Echo current date
      #   run: echo $timestamp
       
      # - name: upload artifact
      #   id: upload-artifact
      #   uses: actions/upload-artifact@v4
      #   if: always()
      #   with:
      #     name: Talentsavvy-Cypress-Test-${{ env.timestamp }}
      #     path: cypress/reports/html
      #     retention-days: 30

      # # - name: Read HTML content
      # #   id: read-html
      # #   run: |
      # #     echo "::set-output name=html_content::$(cat cypress/reports/html/Ts-cypress_report.html)"

      # # - name: Read Cypress report content
      # #   id: read-report
      # #   run: |
      # #     # Read HTML content from the generated file
      # #     report_content=$(cat cypress/reports/html/Ts-cypress_report.html)
      # #     echo “::set-output name=content::$report_content”
      # # - name: echo report
      # #   run: |
      # #     echo "report=$report_content" >> $GITHUB_ENV
      # # - name: Echo content
      # #   run: echo $report

      # # - name: echo env variable
      # #   run: echo "CYPRESS_REPORT_CONTENT=::set-output name=content::$report_content" >> $GITHUB_ENV

      
        
      # - name: List content of the directory
      #   run: ls -al cypress/reports/html
      
      # # - name: Send email with Cypress artifacts
      # #   uses: dawidd6/action-send-mail@v3.9.0
      # #   with:
      # #       server_address: smtp-mail.outlook.com
      # #       server_port: 587
      # #       username: rajat@talentsavvy.com
      # #       password: ${{ secrets.CYPRESS_SMTP_PASSWORD }}
      # #       subject: "Cypress test results for ${{ github.repository }}"
      # #       from: rajat@talentsavvy.com
      # #       to: rajat@talentsavvy.com
      # #       content-type: text/html
      # #       html_body: "file://readme.html"
      # #       attachments: |
      # #         cypress/reports/html/*

      # - name: Send Build Email
      #   uses: juanformoso/action-send-mail@1
      #   with:
      #     server_address: smtp-mail.outlook.com
      #     server_port: 587
      #     username: rajat@talentsavvy.com
      #     password: ${{ secrets.CYPRESS_SMTP_PASSWORD }}
      #     subject: "Cypress test results for ${{ github.repository }}"
      #     body: |
      #       Cypress Test Results:

      #       Result   Passed ✅   Failed ❌   Pending ✋   Skipped ↩️   Duration 🕗
      #       Passing  ✅          $PASSED     $FAILED     $PENDING     $SKIPPED      $DURATION

      #     to: rajat@talentsavvy.com
      #     from: rajat@talentsavvy.com
      #     content_type: text/html

